#social media links
TWITTER_X_URL= "https://twitter.com/Vikus3S"
TWITCH_URL= "https://www.twitch.tv/vikussss3"
YOUTUBE_URL= "https://www.youtube.com/channel/UCWTqiQVIA08vVTJhwy1SaDQ"
LINKEDIN_URL= "https://www.linkedin.com/in/felix-saul-orellana-contreras-971b042a6/"
GITHUB_URL= "https://github.com/VikusS3"
SECONDARY_ACCOUNT_GITHUB_URL= "https://github.com/SaulFOC"
MY_EMAIL= "felix21soc@gmail.com"
MY_EMAIL_EDU= "felix.orellanac@istpargentina.edu.pe"
FACEBOOK_URL= "https://facebook.com/profile.php?id=61554249853628&locale=es_LA"